name: Auto update & PR

on:
  push:
    branches:
      - "master"
  schedule:
    - cron: "0 19 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - name: Config git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Checkout Update Branch
        run: |
          git fetch origin action/auto-update || true
          git checkout -B action/auto-update

      - name: Update source
        id: update
        run: |
          echo "Fetching update..."
          nix run .#update
          git add source.nix

          if git diff --staged --quiet; then
            echo "No changes"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "source.nix changed"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Test Build
        if: steps.update.outputs.changed == 'true'
        run: |
          nix build

      - name: Test Flake
        if: steps.update.outputs.changed == 'true'
        run: |
          nix flake check

      - name: Commit Changes
        if: steps.update.outputs.changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Commit Changes"
          git commit -m "action: auto update source"

      - name: Create Pull Request
        if: steps.update.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto update source.nix"
          base: master
          branch: action/auto-update
          title: "Auto Update source.nix"
          body: "This PR was automatically created by GitHub Actions after running nix update."
